### ISSUE TITLE
Minecraft 1.8 Support?

### ISSUE THREAD

**Issue by moldcraft** [EXTER7/recipedumper#2]

**Comment by moldcraft** [comment]
It will be nice if this mod will be always updated to the latest Minecraft version.

P.S. I can donate LTC/BTC, just let me know.

**Comment by moldcraft** [comment]
I changed just the MC version [here](https://github.com/EXTER7/recipedumper/blob/058b754cd1a10a665c1cdd67b7b1ce56263812dd/build.gradle#L29) to `1.8-11.14.1.1375` but [the build is failing](http://sourcebox.io/9c19c3629bec52002d61b46246c73279).

Is it hard to port this mod to 1.8 ?

**Comment by EXTER7** [comment]
There's now an MC-1.8 branch of the mod: 
https://github.com/EXTER7/recipedumper/tree/MC-1.8

**Comment by moldcraft** [comment]
Thank you!

*Give me your Bitcoin address please.*

**Comment by moldcraft** [comment]
There are some recipes that are not dumped in 1.8, `shapedore` and `shapelessore`.
See this [diff 1.7 -> 1.8](https://www.diffchecker.com/06egg2nl).
At the moment I will copy/paste them manually, but it will be nice if you will fix this.

**Comment by moldcraft** [comment]
Also `minecraft:stone_pressure_plate` and `minecraft:piston` is not present in `items.log`

**Comment by moldcraft** [comment]
There are some recipes that are not dumped in 1.8, `shapedore` and `shapelessore` and a few other, see this [diff 1.7 -> 1.8](https://www.diffchecker.com/06egg2nl).
At the moment I will copy/paste them manually, but it will be nice if you will fix this (maybe there are some new recipes in 1.8 that are not dumped).

----

Also some items are missing in `items.log`

```
recipedumper:item!minecraft:stone_pressure_plate:0 U=tile.pressurePlate||L=Pressure Plate
recipedumper:item!minecraft:stone_pressure_plate:32767 U=tile.pressurePlate||L=Pressure Plate
recipedumper:item!minecraft:piston:0 U=tile.pistonBase||L=Piston
recipedumper:item!minecraft:piston:32767 U=tile.pistonBase||L=Piston
recipedumper:item!minecraft:fire:32767 U=tile.fire||L=Fire
```

**Comment by moldcraft** [comment]
Thank you for [the fix](https://github.com/EXTER7/recipedumper/commit/d8919ca67efcde1170167bcf6d55292765d04422)!

Diff `0.0.7 -> 0.0.7.1`:

* [items.log](https://www.diffchecker.com/9j3w0awm)
* [oredict.log](https://www.diffchecker.com/t2wdodew) (no changes)
* [recipes.log](https://www.diffchecker.com/3acqtjl3)
