### ISSUE TITLE
Convert '@itemName' to ['id:damage', ...]

### ISSUE THREAD

**Issue by moldcraft** [EXTER7/recipedumper#3]
Hi,
Thank you very much for this mod.

----

[I see](https://raw.githubusercontent.com/EXTER7/recipedumper/99ea5827de8864c2716e2470dbb251736fe619c4/examples/vsdump-2014-06-26T152053-recipes.log) that `shapedore` recipes contains `@itemName`, as I understand this means all item variations, 
for e.g. `@plankWood` means 

```
['5:0','5:1','5:2','5:3','5:4','5:5']
```

How to convert [this](https://github.com/EXTER7/recipedumper/blob/058b754cd1a10a665c1cdd67b7b1ce56263812dd/src/main/java/vitzli/recipedumper/lib/Formatter.java#L30) to the above array?

----

Currently I did

```java
...
ItemStack is = aList.get(0);
...
String.format(
    "%d:%d",
    is.getItem().getIdFromItem(is.getItem()),
    is.getItemDamage()
);
```

but this generates only `'5:0'`.
I tried many hours to inspect `is` and `is.getItem()` (and other variables) to find a method, something like `is.getItem().getAllDamageLevels()` but without success.

P.S. I am changing this mod to dump recipes in json format.

**Comment by moldcraft** [comment]
I'm building this [online crafting tool](https://minecraft.space/en/crafting).

Everything seems to work fine except recipes that contains slots which can contain different items (or items with different damage).

![staticshot_09-04-2015_23-08-15](https://cloud.githubusercontent.com/assets/1475489/7075967/9db9557a-df0e-11e4-98c4-0326ded00fae.png) ![staticshot_09-04-2015_23-09-48](https://cloud.githubusercontent.com/assets/1475489/7075976/aa71e516-df0e-11e4-94af-f7f364c6cb6a.png)

----

![staticshot_09-04-2015_23-08-33](https://cloud.githubusercontent.com/assets/1475489/7075982/bcdfed10-df0e-11e4-9a4d-1cf91b617be1.png) ![staticshot_09-04-2015_23-09-20](https://cloud.githubusercontent.com/assets/1475489/7075985/c09c8558-df0e-11e4-8838-c128960412ea.png)

----

![staticshot_09-04-2015_23-10-28](https://cloud.githubusercontent.com/assets/1475489/7075992/cb07787c-df0e-11e4-9524-db6ba805b635.png) ![staticshot_09-04-2015_23-10-57](https://cloud.githubusercontent.com/assets/1475489/7075999/ce00f6d4-df0e-11e4-8943-49f0bea2d002.png)

**Comment by moldcraft** [comment]
I am looking through [the exported recipes](https://raw.githubusercontent.com/EXTER7/recipedumper/99ea5827de8864c2716e2470dbb251736fe619c4/examples/vsdump-2014-06-26T152053-recipes.log) and there are some weird recipes that has output id's greater than `1000`. Use `Ctrl+F` and search `:32767`

![~](http://static.md/96e9fb354c2ffbd6d4834fe2dc29585a.png)

Those can be fixed or just to skip them?

**Comment by vitzli** [comment]
IIRC, `:32767` behaves like filter 'use any of these', while `:0` points to the specific item

**Comment by moldcraft** [comment]
I think I figured it out.

1. `@plankWood` can be found in `...-oredict.log`

    ```
    @plankWood->(minecraft:planks:32767,1)
    ```

2. All `minecraft:planks:*` can be found in `...-items.log`

    ```
    recipedumper:item!minecraft:planks:0 U=tile.wood.oak||L=Oak Wood Planks
    recipedumper:item!minecraft:planks:1 U=tile.wood.spruce||L=Spruce Wood Planks
    recipedumper:item!minecraft:planks:2 U=tile.wood.birch||L=Birch Wood Planks
    recipedumper:item!minecraft:planks:3 U=tile.wood.jungle||L=Jungle Wood Planks
    recipedumper:item!minecraft:planks:4 U=tile.wood.acacia||L=Acacia Wood Planks
    recipedumper:item!minecraft:planks:5 U=tile.wood.big_oak||L=Dark Oak Wood Planks
    recipedumper:item!minecraft:planks:32767 U=tile.wood.oak||L=Oak Wood Planks
    ```

    *I will ignore all `:32767` items from `...-items.log`*

So I will replace `@plankWood` with something like this

```
[(minecraft:planks:0,1),(minecraft:planks:1,1),(minecraft:planks:2,1),(minecraft:planks:3,1),(minecraft:planks:4,1),(minecraft:planks:5,1)]
```

----

Then instead of playing with Java and trying to change the mod to export the data in json, will create a javascript parser to convert the current format to json.

----

@EXTER7 Thank you for https://github.com/EXTER7/recipedumper/commit/3ea1e220275352d587dab1bb5dc358e1203353fb

**Comment by moldcraft** [comment]
> https://github.com/EXTER7/recipedumper/issues/3#issuecomment-92469881
> I will ignore all `:32767` items from `...-items.log`

**Update:** I didn't that because there are items that [has only the `:32767` version](https://github.com/EXTER7/recipedumper/blob/d0f28fa3bdf9f4d1bca5e0eac8254da77d5f46f0/examples/vsdump-2015-04-13T231652-items.log#L291) (without `:0` version)
I just replaced `:32767` with `:0`.

----

I finished [the json converter](https://minecraft.space/void/recipedumper-to-json.html). This is [the json converted to yaml](http://sourcebox.io/4fdbbc90f3b138fedeb03760de6e1b9f/yaml). And this is [the result](https://minecraft.space/en/crafting) :smile: (click on any item to see the recipes)
